<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <AssemblyName>Aprico.Messaging.Xml.Tests</AssemblyName>
      <RootNamespace>Aprico</RootNamespace>
      <Description>Aprico Consultants' Distributed Application Libraries: Unit Tests for XML Messaging Helpers.</Description>
      <IsPackable>false</IsPackable>
   </PropertyGroup>

   <ItemGroup>
      <ProjectReference Include="..\Aprico.Messaging.Xml\Aprico.Messaging.Xml.csproj"/>
   </ItemGroup>

   <ItemGroup>
      <PackageReference Include="Aprico.Unit"/>
      <PackageReference Include="AutoFixture"/>
      <PackageReference Include="AutoFixture.Xunit2"/>
      <PackageReference Include="coverlet.collector">
         <PrivateAssets>all</PrivateAssets>
         <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="FluentAssertions"/>
      <PackageReference Include="Microsoft.NET.Test.Sdk"/>
      <PackageReference Include="xunit"/>
      <PackageReference Include="xunit.analyzers">
         <PrivateAssets>all</PrivateAssets>
         <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="xunit.runner.visualstudio">
         <PrivateAssets>all</PrivateAssets>
         <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
   </ItemGroup>

</Project>
